# for reference see https://docs.travis-ci.com/user/languages/android/
language: android

# The current Travis default is a VM based 16.04 Xenial on GCE.
# As android builds are only supported on Trusty images at this time we explicitly specify dist: trusty.
dist: trusty
os: linux

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
  - openjdk11

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools

    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg

  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses


# Using caching as advices here: https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - ./gradlew clean build
  - ./gradlew test
